from .nodes_loader import NODE_CLASS_MAPPINGS as LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_MAPPINGS
from .nodes_apply import NODE_CLASS_MAPPINGS as APPLY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as APPLY_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**LOADER_MAPPINGS, **APPLY_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**LOADER_DISPLAY_MAPPINGS, **APPLY_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
